apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: accounts-service
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: fdmcontainer/ygoedwig/simpleverticle:351
        ports:
        - containerPort: 8430
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  ports:
    - port: 80
      targetPort: 8430
      name: accounts
      protocol: TCP
  selector:
    app: accounts
  type: LoadBalancer

  #52.168.148.186
  #13.72.77.1
  #52.168.93.89
  #13.72.75.39
  #52.170.211.78
